version: '3.1'

services:
  api:
    build:
      context: .
    image: emr-api
    ports:
      - 8070:8070
    networks:
      - internal

  mysqldb:
    image: mysql:5.6.34
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: emrdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    networks:
      - internal

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
    networks:
      - internal

networks:
    internal: